### ISSUE TITLE
Jellyfin 12: registered pages 404 at #/userpluginsettings (menu entries lead to "Page not found")

### ISSUE THREAD

**Issue by romskidd** [IAmParadox27/jellyfin-plugin-pages#18]
## Summary

On Jellyfin 12.0.0 with Plugin Pages 3.0.0.0, the sidebar/user-menu entries are created correctly, but clicking any of them lands on the web client's "Page not found". This affects every registered page, including Modular Home from your own Home Screen Sections plugin, so it does not look plugin-specific.

Everything on the server side works; the failure is the client-side route.

## Environment

| | |
|---|---|
| Jellyfin | 12.0.0 (Docker, `jellyfin/jellyfin:latest`, linux/amd64) |
| Plugin Pages | 3.0.0.0 |
| File Transformation | 3.0.0.0 (Active, no errors) |
| Home Screen Sections | 3.0.0.0 |
| Web client | Modern layout (default in 12.0) |
| Browser | Chrome 152, hard-reloaded, cache cleared |

Upgraded from 10.11.11, where the same entries worked with Plugin Pages 2.4.11.0.

## Steps to reproduce

1. Jellyfin 12.0.0 with Plugin Pages 3.0.0.0 and File Transformation 3.0.0.0.
2. Have at least one registered page (Modular Home is enough; I also have a third-party plugin registering one).
3. Open the user menu: the entries are listed, with their icons.
4. Click one.

**Expected:** the registered page opens.
**Actual:** "Page not found / Ceci n'est pas la page que vous cherchez."

## What works

- Registration is read and logged at startup:
  ```
  Jellyfin.Plugin.PluginPages.PluginPagesPlugin: Found config.json in /config/plugins/configurations/Jellyfin.Plugin.PluginPages
  Jellyfin.Plugin.PluginPages.PluginPagesPlugin: Registering page: Jellyfin.Plugin.HomeScreenSections Modular Home /ModularHomeViews/settings
  Jellyfin.Plugin.PluginPages.PluginPagesPlugin: Registering page: Jellyfin.Plugin.Simkl RK Simkl Scrobbler /Simkl/Link/Fragment
  TaskManager: PluginPages Startup Completed after 0 minute(s) and 0 seconds
  ```
- The client fetches the page list: `GET /PluginPages/User` is called on load (visible in the browser console).
- The menu entries render, with the correct labels and icons.
- The host page is served: `GET /web/userpluginsettings.html` → 200.
- `GET /web/main.jellyfin.bundle.js` → 200 (519 986 bytes), so the file you transform still exists in 12.0.
- File Transformation registers its transformations without error, including `index.html` (the injected markup contains `PluginPages` and `inject.js`) and `main.jellyfin.bundle.js`.
- The target endpoints themselves answer: `GET /Simkl/Link/Fragment` → 200 with a valid token.

## What fails

The anchor produced for each entry is:

```
#/userpluginsettings.html?pageUrl=/Simkl/Link/Fragment
#/userpluginsettings.html?pageUrl=/ModularHomeViews/settings
```

Navigating there, the 12.0 router rewrites the URL to `#/userpluginsettings?pageUrl=…` (the `.html` suffix is dropped) and then renders its 404 view. No network request is made for the `pageUrl` target.

## Likely cause

Two candidates, both client-side:

1. **Route registration.** In 12.0 the web client moved to a React router; a route injected the 10.11 way is not resolved, and `.html` suffixes are stripped from hash routes.
2. **Host page format.** `/web/userpluginsettings.html` still uses the legacy view markup:
   ```html
   <div id="userPluginPreferencesPage" data-role="page" class="page libraryPage userPreferencesPage noSecondaryNavPage" data-title="${Home}" data-backbutton="true">
   ```
   `data-role="page"` belongs to the old view manager, which the Modern layout no longer mounts.

A stray client-side error also shows up on that navigation, possibly related:

```
TypeError: t.scrollHandler is not a function
    at 49275.<hash>.chunk.js:1:2131
```

## Workaround for users

The registered pages remain reachable at their own address (for a plugin that serves a standalone page), so nothing is lost beyond the menu shortcut.

Happy to test a build or gather any other trace on this instance.

**Comment by romskidd** [comment]
Correction, and apologies for the noise: **this was my mistake, not a bug in Plugin Pages.**

What actually happened: I upgraded to Jellyfin 12 while File Transformation 2.5.11.0 was still installed, which the server disabled. My browser then cached the un-patched `main.jellyfin.bundle.js` from that window. After updating to File Transformation 3.0.0.0 and Plugin Pages 3.0.0.0 and restarting, I tested again without clearing that cache, so the client kept using the old bundle with no route registered, and rendered its 404. That is what I reported.

After a proper cache-clearing reload, everything works: the menu entries open their pages normally, and `#/userpluginsettings.html?pageUrl=…` resolves as expected. I also verified server-side that the served `main.jellyfin.bundle.js` does contain the injected route and that `index.html` references `PluginPages/inject.js`, on both of my instances running Jellyfin 12.0.0 with the 3.0.0.0 plugins.

So the only thing needed after upgrading to 12 is a hard reload once the new plugin versions are in place. Closing this. Thanks for the quick 12.0 builds, and sorry for the false alarm.
